version: "3.9"

services:
  retapis_service:
    image: ret-api-dashboard        # ✅ This will be the image name
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ret-api-dashboard   # ✅ Container will have this exact name
    ports:
      - "5000:5020"
    volumes:
      - .:/app
    restart: always
